name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt

      - run: python -c "import fastapi"

      - run: docker build -t ai-doc-chat .

      - run: |
          docker run -d -p 8000:8000 \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            ai-doc-chat

          echo "Waiting for app to start..."

          for i in {1..10}; do
            curl http://localhost:8000/ && break
            sleep 3
          done

          curl http://localhost:8000/ || exit 1

          
